// source: https://youtu.be/WAMqFdCFotY?t=407

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  // fetch external API
  const res = await fetch("https://jsonplaceholder.typicode.com/todos");
  // get data back in json
  const data = await res.json();

  return {
    props: {
      todos: data,
    },
  };
}

export default function Home({ todos }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js <a href="https://nextjs.org">SSR example </a>
        </h1>

        {/* Using ternary Operator */}

        {/* Using question mark after 'todos' prevent error undefined before rendering */}

        {/* show Loading... while fetch in to page  */}
        {todos?.leght === 0 ? (
          <div>Liading Page.... </div>
        ) : (
          // Otherwise
          // show todos & for every single todo render out on screen
          todos?.map((todo) => (
            <div key={todo.id}>
              <p>
                {todo.id}: {todo.title}
              </p>
            </div>
          ))
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
